export { default as MNIST } from './MNIST';
export { default as Line } from './Line';
export { default as Moons, POLARITY as MOONS_POLARITY } from './Moons';
export { default as Clusters } from './Clusters';
export { default as Stripes } from './Stripes';
export { default as Circles } from './Circles';
export { default as Swirl } from './Swirl';
export { default as BostonHousing } from './BostonHousing';
export { default as ImageNet } from './ImageNet';
export { default as COCO } from './COCO';
